# Users of the plugin will need to set some required configuration values to interact
# with the blockchain. We could have this be set in a generated nftworlds-blockchain.yml file
# or something

polygon_http_rpc: "https://polygon-mainnet.g.alchemy.com/v2/ZZhQH1Yt3EHggV-mBfVGZTrIy9o5XT9M" #this is just an example, end users should set their own RPC used by web3j..
ethereum_http_rpc: "https://eth-mainnet.alchemyapi.io/v2/BJKzGRUBi_0Gc37k55IDF0NIyEOExYsd" #this is just an example, end users should set their own RPC used by web3j..
server_wallet_address: "0x2a52d32b2fB09492ddE1CA2c36E1c69531664461" #used by server as the payment receiver address, and setting state data on players
