polygon_https_rpc: "https://polygon-rpc.com"
ethereum_https_rpc: "https://eth-mainnet.alchemyapi.io/v2/BJKzGRUBi_0Gc37k55IDF0NIyEOExYsd"
server_wallet_address: "0x2a52d32b2fB09492ddE1CA2c36E1c69531664461"
# Starting with 0x.
server_wallet_private_key: ""
contracts:
  polygon_player_contract: "0xF405Fb60690395D8d4d047Cc8916Df256270285f"
  polygon_wrld_contract: "0xD5d86FC8d5C0Ea1aC1Ac5Dfab6E529c9967a45E9"
  ethereum_wrld_contract: "0xD5d86FC8d5C0Ea1aC1Ac5Dfab6E529c9967a45E9"
link-timeout: 1800
debug: false