name: Java Build
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  JDK_VERSION: '17'
  SPIGOT_VERSION: '1.18'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ env.JDK_VERSION }}
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Resolve shaded .jar
      id: resolve-shaded
      run: |
        JAR_PATH=`echo **/wrld-payments-api-*-shaded.jar`
        JAR_NAME=`basename ${JAR_PATH}`

        echo ::set-output name=jar_path::${JAR_PATH}
        echo ::set-output name=jar_name::${JAR_NAME}
    - name: Upload .jar
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.resolve-shaded.outputs.jar_name }}
        path: ${{ steps.resolve-shaded.outputs.jar_path }}
    - name: Extract Release Version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      shell: bash
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
    - uses: papeloto/action-zip@v1
      with:
        files: ${{ steps.resolve-shaded.outputs.jar_path }}
        dest: ${{ steps.resolve-shaded.outputs.jar_name }}.zip
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: WRLD-Payments-API v${{ steps.get_version.outputs.version }}
        files: ${{ steps.resolve-shaded.outputs.jar_path }}.zip
        generate_release_notes: true
