name: Publish package to Maven
on:
  push:
    branches:
      - main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven
          server-id: worldql-partners-releases
          server-username: ${{ secrets.MAVEN_NAME }}
          server-password: ${{ secrets.MAVEN_SECRET }}
        
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish package
        run: mvn -e --batch-mode deploy
